pipeline:

  docker:
    image: plugins/docker
    registry: quay.io
    secrets: [ docker_username, docker_password, docker_email ]
    repo: quay.io/buildo/backporto
    force_tag: true
    tag:
      - latest
      - ${DRONE_COMMIT_SHA}
    when:
      branch: master

  deploy:
    image: appleboy/drone-ssh
    host: jar.srv.buildo.io
    user: root
    port: 22
    secrets: [ ssh_key ]
    command_timeout: 300
    script:
      - crane lift backporto
    when:
      branch: master

